# Host mount point                    Path in backend             Filesystem type
/mnt/storagespace-prosvetlenie        /storage/prosvetlenie       fuse.sshfs
# /mnt/another-storage                /storage/another           fuse.sshfs
